print("              RELATÓRIO FINAL DE DESASTRES")
print("="*60)
print(f"-> Quantidade total de desastres registrados: {quantidade_desastres}")
print("\n-> Total de pessoas afetadas por categoria:")
print(f"   Crianças: {total_criancas} | Adultos: {total_adultos} | Idosos: {total_idosos} |"f" Mobilidade reduzida: {total_mobilidade_reduzida} | Feridos: {total_feridos}")
print(f"\n-> Categoria mais afetada no geral: {categoria_mais_afetada}")
print(f"-> Total geral de pessoas afetadas em todos os desastres: {total_geral_afetados}")
print(f"-> Local do desastre mais grave (maior número de afetados): {desastre_mais_grave_local}")
print("="*60)
print("                   FIM DO RELATÓRIO")
print("="*60)
